version: '2.1'
services:
  postgres:
    image: postgres:12.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: todolist
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
  todolist:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      postgres:
          condition: service_healthy
  